apiVersion: v1
kind: Service
metadata:
  name: chainlink-lb
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: chainlink-lb
spec:
  type: LoadBalancer
  selector:
    app: chainlink-node
  ports:
  - name: cnode-port
    port: 6688
    protocol: TCP
    targetPort: 6688
  sessionAffinity: None
