apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    role: service
spec:
  type: NodePort
  selector:
    app: chainlink-node
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
